from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Text, Float, BigInteger, Date, Boolean, DateTime, ForeignKey
from sqlalchemy.orm import relationship

Base = declarative_base()

class Symbols(Base):
    __tablename__ = "symbol"
    id = Column(Integer, primary_key=True, index=True)
    Csymbol = Column(String(150), unique=True, nullable=False)
    Cname = Column(String(255))
    exchange = Column(String(150))


class StockInfo(Base):
    __tablename__ = "stockinfo"

    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(20), nullable=False)
    name = Column(String(255), nullable=False)
    price = Column(Float)
    changesPercentage = Column(Float)
    change = Column(Float)
    dayLow = Column(Float)
    dayHigh = Column(Float)
    yearHigh = Column(Float)
    yearLow = Column(Float)
    marketCap = Column(BigInteger)
    priceAvg50 = Column(Float)
    priceAvg200 = Column(Float)
    exchange = Column(String(50))
    volume = Column(BigInteger)
    avgVolume = Column(BigInteger)
    open_price = Column(Float)
    previousClose = Column(Float)
    eps = Column(Float)
    pe = Column(Float)
    onedayvolatility = Column(String(100))
    timestamp = Column(Date)

class CompanyProfile(Base):
    __tablename__ = "companyprofile"

    id = Column(Integer, primary_key=True, index=True)
    symbol = Column(String(10), nullable=False)
    price = Column(Float)
    beta = Column(Float)
    volAvg = Column(BigInteger)
    mktCap = Column(BigInteger)
    lastDiv = Column(Float)
    price_range = Column(String(255))
    changes = Column(Float)
    companyName = Column(String(255))
    currency = Column(String(10))
    cik = Column(String(20))
    isin = Column(String(20))
    cusip = Column(String(20))
    exchange = Column(String(100))
    exchangeShortName = Column(String(50))
    industry = Column(String(100))
    website = Column(String(255))
    description = Column(Text)
    ceo = Column(String(100))
    sector = Column(String(50))
    country = Column(String(50))
    fullTimeEmployees = Column(Integer)
    phone = Column(String(50))
    address = Column(Text)
    city = Column(String(50))
    state = Column(String(50))
    zip_code = Column(String(20))
    dcfDiff = Column(Float)
    dcf = Column(Float)
    image = Column(String(255))
    ipoDate = Column(Date)
    defaultImage = Column(Boolean)
    isEtf = Column(Boolean)
    isActivelyTrading = Column(Boolean)
    isAdr = Column(Boolean)
    isFund = Column(Boolean)


class StockPerformance(Base):
    __tablename__ = 'stockperformance'
    
    id = Column(BigInteger, primary_key=True, autoincrement=True)
    symbol = Column(String(10), nullable=False, unique=True)
    one_day = Column(Float)
    five_day = Column(Float)
    one_month = Column(Float)
    three_month = Column( Float)
    six_month = Column(Float)
    ytd = Column(Float)  
    one_year = Column( Float)
    three_year = Column(Float)
    five_year = Column(Float)
    ten_year = Column(Float)
    max_val = Column(Float)

class FinancialMetrics(Base):
    __tablename__ = 'financialmetrics'

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(10), nullable=False, unique=True)
    dividendYielTTM = Column(Float)
    dividendYielPercentageTTM = Column(Float)
    peRatioTTM = Column(Float)
    pegRatioTTM = Column(Float)
    payoutRatioTTM = Column(Float)
    currentRatioTTM = Column(Float)
    quickRatioTTM = Column(Float)
    cashRatioTTM = Column(Float)
    daysOfSalesOutstandingTTM = Column(Float)
    daysOfInventoryOutstandingTTM = Column(Float)
    operatingCycleTTM = Column(Float)
    daysOfPayablesOutstandingTTM = Column(Float)
    cashConversionCycleTTM = Column(Float)
    grossProfitMarginTTM = Column(Float)
    operatingProfitMarginTTM = Column(Float)
    pretaxProfitMarginTTM = Column(Float)
    netProfitMarginTTM = Column(Float)
    effectiveTaxRateTTM = Column(Float)
    returnOnAssetsTTM = Column(Float)
    returnOnEquityTTM = Column(Float)
    returnOnCapitalEmployedTTM = Column(Float)
    netIncomePerEBTTTM = Column(Float)
    ebtPerEbitTTM = Column(Float)
    ebitPerRevenueTTM = Column(Float)
    debtRatioTTM = Column(Float)
    debtEquityRatioTTM = Column(Float)
    longTermDebtToCapitalizationTTM = Column(Float)
    totalDebtToCapitalizationTTM = Column(Float)
    interestCoverageTTM = Column(Float)
    cashFlowToDebtRatioTTM = Column(Float)
    companyEquityMultiplierTTM = Column(Float)
    receivablesTurnoverTTM = Column(Float)
    payablesTurnoverTTM = Column(Float)
    inventoryTurnoverTTM = Column(Float)
    fixedAssetTurnoverTTM = Column(Float)
    assetTurnoverTTM = Column(Float)
    operatingCashFlowPerShareTTM = Column(Float)
    freeCashFlowPerShareTTM = Column(Float)
    cashPerShareTTM = Column(Float)
    operatingCashFlowSalesRatioTTM = Column(Float)
    freeCashFlowOperatingCashFlowRatioTTM = Column(Float)
    cashFlowCoverageRatiosTTM = Column(Float)
    shortTermCoverageRatiosTTM = Column(Float)
    capitalExpenditureCoverageRatioTTM = Column(Float)
    dividendPaidAndCapexCoverageRatioTTM = Column(Float)
    priceBookValueRatioTTM = Column(Float)
    priceToBookRatioTTM = Column(Float)
    priceToSalesRatioTTM = Column(Float)
    priceEarningsRatioTTM = Column(Float)
    priceToFreeCashFlowsRatioTTM = Column(Float)
    priceToOperatingCashFlowsRatioTTM = Column(Float)
    priceCashFlowRatioTTM = Column(Float)
    priceEarningsToGrowthRatioTTM = Column(Float)
    priceSalesRatioTTM = Column(Float)
    enterpriseValueMultipleTTM = Column(Float)
    priceFairValueTTM = Column(Float)
    dividendPerShareTTM = Column(Float)

class TechnicalIndicator(Base):
    __tablename__ = "rsitechnicalindicator"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20))
    date = Column(Date)
    open_price = Column(Float)
    high = Column(Float)
    low = Column(Float)
    close = Column(Float)
    volume = Column(BigInteger)
    rsi = Column(Float)

class FinancialGrowth(Base):
    __tablename__ = "financialgrowth"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(20))
    date = Column(Date)
    calendarYear = Column(String(10))
    period = Column(String(10))
    revenueGrowth = Column(Float)
    grossProfitGrowth = Column(Float)
    ebitgrowth = Column(Float)
    operatingIncomeGrowth = Column(Float)
    netIncomeGrowth = Column(Float)
    epsgrowth = Column(Float)
    epsdilutedGrowth = Column(Float)
    weightedAverageSharesGrowth = Column(Float)
    weightedAverageSharesDilutedGrowth = Column(Float)
    dividendsperShareGrowth = Column(Float)
    operatingCashFlowGrowth = Column(Float)
    freeCashFlowGrowth = Column(Float)
    tenYRevenueGrowthPerShare = Column(Float)
    fiveYRevenueGrowthPerShare = Column(Float)
    threeYRevenueGrowthPerShare = Column(Float)
    tenYOperatingCFGrowthPerShare = Column(Float)
    fiveYOperatingCFGrowthPerShare = Column(Float)
    threeYOperatingCFGrowthPerShare = Column(Float)
    tenYNetIncomeGrowthPerShare = Column(Float)
    fiveYNetIncomeGrowthPerShare = Column(Float)
    threeYNetIncomeGrowthPerShare = Column(Float)
    tenYShareholdersEquityGrowthPerShare = Column(Float)
    fiveYShareholdersEquityGrowthPerShare = Column(Float)
    threeYShareholdersEquityGrowthPerShare = Column(Float)
    tenYDividendperShareGrowthPerShare = Column(Float)
    fiveYDividendperShareGrowthPerShare = Column(Float)
    threeYDividendperShareGrowthPerShare = Column(Float)
    receivablesGrowth = Column(Float)
    inventoryGrowth = Column(Float)
    assetGrowth = Column(Float)
    bookValueperShareGrowth = Column(Float)
    debtGrowth = Column(Float)
    rdexpenseGrowth = Column(Float)
    sgaexpensesGrowth = Column(Float)
